version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./tinyfilemanager:/var/www/html
      - ./logs/nginx:/var/log/nginx
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf
      # map a harddisk to a directory in the container
      - /media/hrk/SOILENT:/var/www/html/files:rw
  php:
    image: php:fpm-alpine
    restart: always
    networks:
      - internal
    volumes:
      - ./tinyfilemanager:/var/www/html
      - ./logs/php.log:/var/log/fpm-php.www.log
      - /media/hrk/SOILENT:/var/www/html/files:rw
networks:
  internal:
    driver: bridge
